cargo-features = ["edition2024"]

[package]
name = "quake-test-support"
version.workspace = true
edition = "2024"
repository.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]

[lints]
workspace = true
